### PR TITLE
Milestone 1

### PR DESCRIPTION
**Pull request by mikethreels**
# Milestone 1
- created the requested Enumerable methods.
- included test.RB file to test our method outputs.
- worked with git-flow

### CODE REVIEW

**Review by MarioDena — CHANGES_REQUESTED** [review]
Hello! Good work on implementing your methods, 🎖️  however there are changes that need to be made.

## Changes required 🔴 

- [x]  my_each is not handling ranges and hashes correctly when a block is given. 

- [x] my_all should return false if the block returns false or nil::range, also you are not handling classes, regex and patterns correctly.

- [x] same problem from my_all is present on my_any also when no block or argument is given it should return false if at least one of the collection is not true.

- [x] Same problem not handling classes, regex and patterns is present on my_none? also it should return false if the block ever returns true for all elements::range.

- [x] my_count should return the number of items in enum through enumeration::range, and counts the number of items in enum that are equal to item if an argument is given

- [x] my_map should return a new array with the results of running a given block once for every element in enum::range

- [x] my_inject is not handling blocks and symbols with enum and it should raise a "LocalJumpError" when no block or argument is given.

- [x] multiply_els should accept an array as an argument and multiplies all the elements of the array together using #my_inject.

For reference I recommend you to read this: https://ruby-doc.org/core-2.6.5/Enumerable.html evey test case is explained over there.

Also a screenshot for reference GitHub Logo

**Comment by Bismarck-GM** [comment]
# Milestone 2:

- Re-factor My_each mainly changed length for size and almost all methods that use it worked.
- Added helper methods for checking Regex expressions
- Added Error codes for methods
- Added more test cases. Copied them from the Ruby Docs that TSE sent us.

**Comment by lekegitrepo** [comment]
#### Hi @mikethreels and @Bismarck-GM :clap:
#### Good job so far. However, the test case on line 28 and 35 of the test.rb is not working, check and fix it before submitting for another review.

**_The test cases are:_**

- **_`my_text.my_all?(/t/) { |value| value >= 2 }`_**

- **_`my_text.my_any?(/t/) { |value| value >= 2 }`_**

#### _Reviewed by Temitayo Adeleke._

**Review by lekegitrepo — CHANGES_REQUESTED** [review]
#### Status: Request changes

**Comment by lekegitrepo** [comment]
#### Good job @mikethreels and @Bismarck-GM :clap: :clap:
#### This project is approved.

#### _Reviewed by Temitayo Adeleke._

**Review by lekegitrepo — APPROVED** [review]
#### Status: Approved.

**Pull request merged**
